### ISSUE TITLE
Cursor does not hide when urxvt or Chromium has focus under JWM

### ISSUE THREAD

**Issue by rhester72** [jcs/xbanish#13]
Using jwm (Joe's Window Manager), use of urxvt or Chromium on Arch Linux prevents the cursor from being hidden (and running in debug mode shows that xbanish doesn't "see" the keystrokes, either).  I've tried the latest git and the prior one that had the "-p" option added, both behave the same.

Interestingly, if I put focus on a basic xterm window, xbanish works as designed.

**Comment by jcs** [comment]
This should be fixed with 1.4.
