### ISSUE TITLE
Cursor isn't fully hidden

### ISSUE THREAD

**Issue by losingkeys** [jcs/xbanish#14]
Possibly related to #13, when in firefox or chromium with xbanish turned on, I still see links/etc hovered over (they're underlined, change colors, etc).

**Comment by jcs** [comment]
That is somewhat to be expected since the cursor is not moved, just hidden.  There would probably be other issues related to moving the cursor (focus-follows-mouse, `xautolock` hot corners, etc.)

**Comment by losingkeys** [comment]
I wasn't thinking of moving the cursor, but I figured there might be some
way I'm X to either disable the cursor hover or the whole cursor altogether.

That is somewhat to be expected since the cursor is not moved, just hidden.
There would probably be other issues related to moving the cursor
(focus-follows-mouse, xautolock hot corners, etc.)

—
Reply to this email directly or view it on GitHub
<https://github.com/jcs/xbanish/issues/14#issuecomment-108949341>.
