### ISSUE TITLE
a cursor is not become visible in chromium

### ISSUE THREAD

**Issue by MaximKraev** [jcs/xbanish#16]
a cursor is stay invisible after mouse moved above chromium. no "mouse moved" events in debug log until the mouse leaves Chromium window, after the cursor become visible. Chromium - 38.0.2125.111, xbanish - the latest master.

**Comment by kucharskim** [comment]
Same here with OpenBSD, xbanish-1.3p0 and chromium-42.0.2311.135p0

**Comment by jcs** [comment]
Can you both try the code I just committed in 731fa79?

**Comment by kucharskim** [comment]
@jcs, so far I don't see any issues with 731fa79. It works like a charm. No more issues with Chromium.
