### ISSUE TITLE
Cursor keeps hidden when trackpoint button is used insted of trackpad or mouse

### ISSUE THREAD

**Issue by chilicuil** [jcs/xbanish#17]
I have a thinkpad edge laptop running xbanish 5c0aed74bac847221bf7efd2fad955362ac8cc77 on Ubuntu 12.04 and the cursor keeps hidden when the trackpoint button is used instead of the trackpad or a regular mouse.

http://i.imgur.com/MwUTeKy.jpg

Testcase.
1. Start xbanish
2. Type something, the cursor disappears
3. Use the mouse or the trackpad to make the cursor appear
4. Type again, the cursor disappears
5. Use the trackpoint button to move the mouse, the cursor keeps being hidden even when it reacts to movement (I can see links being marked)

**Comment by jcs** [comment]
Can you try the code in 731fa79?  It uses a different input mechanism which might help with this.

**Comment by jcs** [comment]
Probably fixed with 1.4.  If not, re-open this.
