### ISSUE TITLE
how can I build this under Ubuntu?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jcs/xbanish#23]
I tried:

$ make

cc -O2 -Wall -Wunused -Wmissing-prototypes -Wstrict-prototypes -I/usr/X11R6/include -c xbanish.c -o xbanish.o
xbanish.c:38:35: fatal error: X11/extensions/Xfixes.h: No such file or directory
 #include <X11/extensions/Xfixes.h>
                                   ^
compilation terminated.
make: *** [xbanish.o] Error 1

**Comment by jcs** [comment]
You probably need some `-dev` package installed that has that header.

**Comment by vitaly-zdanevich** [comment]
You have no idea what the package I need?

**Comment by chilicuil** [comment]
@vitaly-zdanevich you need x11proto-core-dev, libx11-dev, libxt-dev, libxfixes-dev, libxi-dev, https://github.com/minos-org/xbanish-deb/blob/master/debian/control#L5 , also if interested I maintain a repository where night builds of xbanish are available https://launchpad.net/~minos-archive/+archive/ubuntu/main

**Comment by jcs** [comment]
Thanks @chilicuil.

**Comment by vitaly-zdanevich** [comment]
@chilicuil maybe you will add link to ppa to README?
