### ISSUE TITLE
RFE: Move cursor off screen/to corner when hidden

### ISSUE THREAD

**Issue by Stebalien** [jcs/xbanish#24]
Currently, even though the cursor is hidden visually, it's still there. This means that the hover effect is still triggered which can be mildly irritating. It would be nice to have an option to move the cursor to the corner (or off screen?) while hidden (coming back to its original position when unhidden) so this doesn't happen.

**Comment by jcs** [comment]
Hi, I implemented this in abdb8359ae2 with the `-m` option.  It can be used like `-m se` to move it to the southeast corner of the screen when hiding.
