### ISSUE TITLE
roll new version

### ISSUE THREAD

**Issue by bahamas10** [jcs/xbanish#34]
i've been using xbanish custom compiled on my machine for the last month or so with this change https://github.com/jcs/xbanish/pull/31 and it's been great.  I'd love to see a new version get cut and available as a GitHub release, since the version of `xbanish` provided by my package manager (xbps on Void Linux) is outdated and doesn't include that fix, and is built using the 1.5 tarball from github.

**Comment by jcs** [comment]
A [1.6 release](https://github.com/jcs/xbanish/releases) has been made.
