### ISSUE TITLE
Problem with imagemagick (after a recent update)

### ISSUE THREAD

**Issue by aksr** [jcs/xbanish#36]
*(Note: I'm not sure if this is something `imagemagick` developers must address, anyway...)* 

If the cursor is hidden, executing `import screenshot.png` doesn't show the cursor, instead it just blocks mouse (still invisible), and the only way to *unfreeze* everything is by a keyboard (ctrl+alt+f#) and killing `import`. 
This command demands a cursor (to select the area for screenshot).

On the other hand, executing `import -window root screenshot.png`, works fine.

(Versions of `imagemagick` affected are *after* `7.0.8.41`.)

**Comment by jcs** [comment]
I only have access to ImageMagick 6.9 which doesn't exhibit the problem, but I'm not sure what xbanish is supposed to do differently here.  It just calls `XFixesHideCursor` to hide the cursor and not much else.  It's not doing any active grabs that could be blocking ImageMagick.

I would recommend filling a bug with them about it.
