### ISSUE TITLE
How to install ? 

### ISSUE THREAD

**Issue by Shaltz** [jcs/xbanish#47]
Hi, 

stupid question, but I can't find an answer anywhere...

how to install xbanish on ubutu 20.04 ? On 18.04 I could rely on Minos ppa 
but it doesn't seem to work anymore for 20.04...

so, how do I install it ? I can't find info anywhere on how to compile it, how to dl a deb package (is there a deb package somewhere ?) or else... 

thanks in advance

**Comment by jsarasin** [comment]
You'll likely need a few packages first:
```bash
sudo apt-get update
sudo apt-get install build-essential git-all
```
Then you'll need to compile it and set it to run in .xinitrc for the next time you boot up.

```bash
cd ~
git clone https://github.com/jcs/xbanish.git
cd xbanish
make
echo "~/xbanish/xbanish" >> ~/.xinitrc
```

To get using it right away:
```bash
./xbanish &
```

That's the most basic way to get it up and running. Hopefully I got everything, but if you have any problems let me know.

**Comment by javier-lopez** [comment]
Minos maintainer here, xbanish has been built and uploaded to the main ppa for the latest Ubuntu 20.04 release, have a nice day everyone :+1: 

    $ sudo add-apt-repository ppa:minos-archive/main
    $ sudo apt-get update; sudo apt-get install -y xbanish

**Comment by Shaltz** [comment]
whoa, you are, both of you, starts :) :)
thanks so much for you're quick help

I'll give it a try right away

**Comment by dhruv-dave** [comment]
When i try to build this library, i get an error. 

Steps followed:
```
$ sudo apt-get update
$ sudo apt-get install build-essential git-all
```
Error:
```
 cd ~/installs/xbanish/xbanish 
$ make
cc -O2 -Wall -Wunused -Wmissing-prototypes -Wstrict-prototypes -Wunused -I/usr/X11R6/include -c xbanish.c -o xbanish.o
xbanish.c:27:10: fatal error: X11/Intrinsic.h: No such file or directory
   27 | #include <X11/Intrinsic.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:28: xbanish.o] Error 1
```
