### ISSUE TITLE
Memory leak on Arch / system freeze

### ISSUE THREAD

**Issue by vtnpp** [jcs/xbanish#48]
The issue started to occur recently.

Setup: Arch Linux + bspwm + [`xbanish-git` <sup>AUR</sup>](https://aur.archlinux.org/packages/xbanish-git/). I launch `xbanish` with `xbanish &` in my `.xinitrc` file.

Sometimes, when I leave my machine and come back after about 15 minutes, i3lock keystrokes registering lags really hard when typing my password to unlock my session.

After unlocking, everything starts to lag really hard too. My RAM consumption keeps growing until it reaches 100% and my system eventually freezes. I'm then forced to reboot manually.

This time around, I managed to quickly launch `ytop` to see which process was the culprit and turns out it was `xbanish`, which was eating about 35% of my 16GB of RAM.

Would it be due to #46 by any chance?

**Comment by jcs** [comment]
I don't know, why not test it?

**Comment by vtnpp** [comment]
> I don't know, why not test it?

I'm using [`xbanish-git`<sup>AUR</sup>](https://aur.archlinux.org/packages/xbanish-git/) so I'm already using latest commit

`pacman -Qi xbanish-git`:
```
Name            : xbanish-git
Version         : 1.6.r8.g80c630f-1
```

**Comment by jcs** [comment]
Can you try with 21aef975?

**Comment by vtnpp** [comment]
I've just updated to 21aef97

`pacman -Qi xbanish-git`:

```
Name            : xbanish-git
Version         : 1.6.r11.g21aef97-1
```

Thanks!

**Comment by jcs** [comment]
Also, if you have the ability to run it with `-d` and capture the output, I want to make sure it's not chewing up CPU time repeatedly calling `snoop_root` from a `device_change_type` event.

**Comment by vtnpp** [comment]
Now I remember something I completely forgot to mention.

The issue occurred maybe four or five times exclusively in the evening, after unplugging/re-plugging my mouse and keyboard (I clean both every evening).

Now that I updated to your latest commits, I've just tried to unplug and re-plug both and didn't have any issue so I guess it's solved. I'll wait for a few more days just to make sure and report back.

I'm almost certain it was due to #46 because I last updated [`xbanish-git`<sup>AUR</sup>](https://aur.archlinux.org/packages/xbanish-git/) on May 2nd and the issue started to occur around this date.

`xbanish -d >output.txt 2>&1` only lists some of my devices and events such as "mouse moved" or "keystroke, hiding cursor", nothing else. Nothing related to `snoop_root` or `device_change_type`.

Just to make sure, are you only interested in the beginning of the output or am I supposed to let it run for an extensive period of time?

I assume it's the first option, it's going to be a trillion lines output if I wait for a day, the file already has over 60k lines of "mouse moved, already unhiding cursor" and is over 22MB after maybe 15 seconds only.

**Comment by jcs** [comment]
I'm interested in seeing whether it goes into a loop when you unplug and re-plug your devices (a `device_change_type` event appearing over and over).  That would explain why it would eat up tons of memory before 21aef97, but that commit just fixes the memory leak.  If the event keeps appearing, it's going to keep eating CPU time and would need to be addressed.

**Comment by vtnpp** [comment]
Oh ok, sorry.

I've just had what you describe actually.

`xbanish -d` output keeps printing this endlessly as soon as I unplug/re-plug my keyboard:

![01](https://user-images.githubusercontent.com/59181811/81433781-64f93700-9165-11ea-98c9-8780ff1816ce.png)

Then the memory leak starts.

**Comment by jcs** [comment]
I think e54bdd8 should fix this, if you can try that out and make sure it doesn't print those attach messages in a loop, nor consume any extra memory.

**Comment by vtnpp** [comment]
Looks like e54bdd8 did the trick.

I unplugged/re-plugged both my keyboard and mouse several times, `xbanish -d &` only prints the messages shown in my previous screenshots when the plug/unplug occurs.

So no more loop and therefore no more crazy memory consumption.

Thank you!

**Comment by jcs** [comment]
Thanks for testing, I've created a v1.7 release with these fixes.
