### ISSUE TITLE
Does not start as a systemd service

### ISSUE THREAD

**Issue by DasJott** [jcs/xbanish#56]
I created a systemd service file to start xbanish.  
```
[Unit]
Description=xbanish
After=default.target

[Service]
Type=simple
ExecStart=/usr/bin/xbanish
Restart=on-failure
StartLimitBurst=10
RestartSec=30

[Install]
WantedBy=default.target
```

It doesn't work:
```
Dez 11 11:21:42 jwe systemd[1]: Started xbanish hides mouse cursor on typing.
Dez 11 11:21:42 jwe xbanish[619384]: xbanish: can't open display
Dez 11 11:21:42 jwe systemd[1]: xbanish.service: Main process exited, code=exited, status=1/FAILURE
Dez 11 11:21:42 jwe systemd[1]: xbanish.service: Failed with result 'exit-code'.
```

**Comment by DasJott** [comment]
Okay, gotta put the unit file into .config/systemd/user and start it with flag --user

**Comment by gurghet** [comment]
Sorry, I'm new to Linux, how do you do it so that it runs at startup?

**Comment by DasJott** [comment]
@gurghet additionally to the described steps you have to execute the following in Terminal:
`sudo systemctl enable --now xbanish.service`

**Comment by gurghet** [comment]
thanks a lot, one last question, where do i put the file? i dont have the .configure path
