### ISSUE TITLE
xbanish doesn't hide cursor after x seconds after starting xsession

### ISSUE THREAD

**Issue by Rentib** [jcs/xbanish#68]
I'm running dwm on arch linux, in xinitrc I added 
`xbanish -t 5 -i all -s &`.
After starting xsession (with startx) cursor doesn't disappear after 5 seconds.
After some kind of event (mouse movement / keypress) it works fine.
Is it intended behavior?

**Comment by Ckath** [comment]
yes, I ran into some issues starting the auto hide before x was fully started (personally start it from .xinitrc) where it tried to call `hide_cursor` before x was fully there, which segfaulted it.
for this reason the hide timeout(set_alarm) only starts after the first succesfull 'show_cursor', which is triggered by any kind of event
https://github.com/jcs/xbanish/blob/8543a6180a671b58c69540c9efea2760f92d8664/xbanish.c#L367-L376
it being initially started and resetted by the same line seemed very convinient and clean at the time. a workaround would be to manually fire some x event through xdotool or othermeans, if you need this for some kiosk type application.
